---
- name: Ensure Tomcat8 packages are installed (RedHat).
  yum:
    name: ['tomcat8']
    state: present
  when: ansible_os_family == 'RedHat'

- name: Update apt cache (Debian).
  apt:
    update_cache: yes
    cache_valid_time: 86400
  when: ansible_os_family == 'Debian'

- name: Ensure Tomcat8 is installed (Debian).
  apt:
    name: ['tomcat8', 'tomcat8-admin']
    state: present
  when: ansible_os_family == 'Debian'

- name: copy tomcat defaults file
  template:
    src: 'tomcat8-defaults.j2'
    dest: '/etc/default/tomcat8'
    backup: yes
    owner: root
    group: root
    mode: 0644
  notify: restart tomcat

- name: Copy tomcat8 server.xml.
  template:
    src: server.xml.j2
    dest: /etc/tomcat8/server.xml
    owner: root
    group: root
    mode: 0644
  notify: restart tomcat

- name: Ensure tomcat8 is running.
  service:
    name: tomcat8
    state: started
    enabled: yes
  when: tomcat8_enabled

